package:
  name: r-rjsonio
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.3_0"

source:
  fn: RJSONIO_1.3-0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/RJSONIO_1.3-0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/RJSONIO/RJSONIO_1.3-0.tar.gz
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  # Imports: methods
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RJSONIO')" # [not win]
    - "\"%R%\" -e \"library('RJSONIO')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: BSD_3_clause + file LICENSE
  #summary:

# The original CRAN metadata for this package was:

# Package: RJSONIO
# Version: 1.3-0
# License: BSD_3_clause + file LICENSE
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml