package:
  name: r-proxy
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.4_14"

source:
  fn: proxy_0.4-14.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/proxy_0.4-14.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/LDAvis/proxy_0.4-14.tar.gz
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  #Suggests: cba
  build:
    - r >=2.4.0

  run:
    - r >=2.4.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('proxy')" # [not win]
    - "\"%R%\" -e \"library('proxy')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  #summary:

# The original CRAN metadata for this package was:

# Package: proxy
# Version: 0.4-14
# License: GPL-2
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml