package:
  name: topik
  version: 0.3.1

source:
  git_url: git://github.com/ContinuumIO/topik.git
  git_tag: v0.3.1

requirements:
  build:
    - python
    - setuptools
    - ijson
    - pysolr
    - blaze
    - bokeh
    - numpy
    - pandas
    - gensim
    - pattern
    - textblob
    - click
    - solrpy
    - elasticsearch-py
    - nltk
    - pyldavis
    - matplotlib
    - smart_open
    - setuptools-markdown
    - jsonpickle
    - versioneer

  run:
    - python
    - blaze
    - bokeh
    - numpy
    - pandas
    - gensim
    - pattern
    - textblob
    - click
    - solrpy
    - elasticsearch-py
    - nltk
    - ijson
    - pysolr
    - pyldavis
    - matplotlib
    - smart_open
    - jsonpickle

build:
  # Optional Python entry points
  entry_points:
    # This creates an entry point named topik that calls
    # topik.cli.run()
    - topik = topik.simple_run.cli:run

test:
  imports:
    - topik

about:
  home: http://github.com/ContinuumIO/topik/
  license: BSD
  summary: 'A Python Topic Modeling toolkit'
