package:
  name: r-data.table
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.9.4"

source:
  fn: data.table_1.9.4.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/data.table_1.9.4.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/data.table/data.table_1.9.4.tar.gz
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  # Imports: methods, chron, reshape2
  # Suggests: ggplot2 (≥ 0.9.0), plyr, reshape, testthat (≥ 0.4), hexbin, fastmatch, nlme, xts, bit64
  build:
    - r >=2.14.0
    - r-reshape2
    - r-chron

  run:
    - r >=2.14.0
    - r-reshape2
    - r-chron

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('data.table')" # [not win]
    - "\"%R%\" -e \"library('data.table')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2, GPL-3
  #summary:

# The original CRAN metadata for this package was:

# Package: data.table
# Version: 1.9.4
# License: GPL-2, GPL-3
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml