package:
  name: r-ldavis
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.2"

source:
  fn: LDAvis_0.2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/LDAvis_0.2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/LDAvis/LDAvis_0.2.tar.gz
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  # Imports: proxy, RJSONIO, parallel
  # Suggests: mallet, lda, topicmodels, gistr (≥ 0.0.8.99), servr, shiny, knitr, rmarkdown
  build:
    - r >=2.10
    - r-proxy
    - r-rjsonio

  run:
    - r >=2.10
    - r-proxy
    - r-rjsonio

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('LDAvis')" # [not win]
    - "\"%R%\" -e \"library('LDAvis')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: MIT + file LICENSE
  #summary:

# The original CRAN metadata for this package was:

# Package: LDAvis
# Version: 0.2
# License: MIT + file LICENSE
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml