package:
  name: solrpy
  version: "0.9.6"

source:
  fn: solrpy-0.9.6.tar.gz
  url: https://pypi.python.org/packages/source/s/solrpy/solrpy-0.9.6.tar.gz
  md5: 5fde85d44010521179a223cde1cc4007
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - solrpy = solrpy:main
    #
    # Would create an entry point called solrpy that calls solrpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - solr
    #- solrpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/solrpy
  license: http://opensource.org/licenses/apache2.0.php
  summary: 'Client for the Solr search service'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
