package:
  name: versioneer
  version: "0.15"

source:
  git_url: https://github.com/warner/python-versioneer
  git_tag: 0.15

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  files:
    - setup.py
    - setup.cfg
  commands:
    - git init
    - git add *
    - git commit -m "initial commit"
    - versioneer install

about:
  home: https://github.com/warner/python-versioneer
  license: Public Domain
