#!/usr/bin/env python
import sys
from collections import Counter
import yaml
import nltk
from topik.utils import html2text
from topik.readers import iter_documents_folder

stop = nltk.corpus.stopwords.words('english')


def histogram(*folders):
    lemmatizer = nltk.stem.WordNetLemmatizer()
    counter = Counter()
    for folder in folders:
        for fname, html in iter_documents_folder(folder):
            content = html2text(html)
            for word in content.split():
                stem = lemmatizer(word)
                counter[stem] += 1
    return counter

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Please specify one or more directories of HTML documents")
        sys.exit()
    #yaml.dump(histogram(sys.argv[1:]))
    print(histogram(*sys.argv[1:]))
