package:
  name: r-chron
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.3_45"

source:
  fn: chron_2.3-45.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/chron_2.3-45.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/chron/chron_2.3-45.tar.gz
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  # Imports: graphics, stats
  # Suggests: scales, ggplot2
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('chron')" # [not win]
    - "\"%R%\" -e \"library('chron')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  #summary:

# The original CRAN metadata for this package was:

# Package: chron
# Version: 0.2
# License: GPL-2
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml