package:
  name: topik
  version: "0.2.0"

build:
  number: 0
  #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}
  #preserve_egg_dir: yes

  # Optional Python entry points
  entry_points:
    # This creates an entry point named topik that calls
    # topik.cli.run()
    - topik = topik.cli:run

source:
  #git_url: git://github.com/ContinuumIO/topik.git
  #git_tag: v0.1.0
  path: ../

requirements:
  build:
    - python
    - setuptools
    - versioneer
    - ijson
    - pysolr
    - blaze
    - bokeh
    - numpy
    - pandas
    - gensim
    - pattern
    - textblob
    - click
    - solrpy
    - elasticsearch
    - nltk
    - pyldavis
    - matplotlib
    - smart_open

  run:
    - python
    - blaze
    - bokeh
    - numpy
    - pandas
    - gensim
    - pattern
    - textblob
    - click
    - solrpy
    - elasticsearch
    - nltk
    - ijson
    - pysolr
    - pyldavis
    - matplotlib
    - smart_open

test:
  imports:
    - topik

about:
  home: http://github.com/ContinuumIO/topik/
  license: BSD
  summary: 'A Python Topic Modeling toolkit'
